In [1]:
import numpy as np

### 1. Create a Numpy array with the following values [1,2,3,4,5]

In [2]:
array1 = np.array([1,2,3,4,5,6])

In [3]:
print(array1)

[1 2 3 4 5 6]


### 2. Print the shape of the aarray1 using the .shape attribute

In [4]:
array1.shape

(6,)

### 3. Reshape the array 1 into a 2D array with 2rows and 3 columns

In [5]:
array_2d = array1.reshape(2, 3)

print(array_2d)

[[1 2 3]
 [4 5 6]]


### 4. Print the shape of the new array.

In [6]:
array_2d.shape

(2, 3)

### 5. Create a second NumPy array with the following values: [6, 7, 8, 9, 10].

In [8]:
array2 = np.array([7,8,9,10,11, 12])
array3 = array2.reshape(2,3)

In [9]:
print(array3)

[[ 7  8  9]
 [10 11 12]]


### 6. Concatenate the two arrays together horizontally.

In [10]:
array2 = np.array([[1],[2],[3],[4],[5],[6]])
array3 = np.array([[7],[8],[9],[10],[11], [12]])
result = np.hstack((array2, array3))

### 7. Print the resulting array

In [11]:
print("Resulting array:")
print(result)

Resulting array:
[[ 1  7]
 [ 2  8]
 [ 3  9]
 [ 4 10]
 [ 5 11]
 [ 6 12]]


### 8. Compute mean, median, and standard deviation

In [12]:
mean = np.mean(result)
median = np.median(result)
std_dev = np.std(result)

print("Mean:", mean)
print("Median:", median)
print("Standard Deviation:", std_dev)

Mean: 6.5
Median: 6.5
Standard Deviation: 3.452052529534663
